#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.5
#  in conjunction with Tcl version 8.6
#    Aug 08, 2022 01:12:08 PM EDT  platform: Windows NT
import os
import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import mainProg




def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = mainProg.Toplevel1(_top1)
    root.mainloop()

if __name__ == '__main__':
    mainProg.start_up()




